package doan.entity;
// Generated Jun 2, 2019 10:14:31 PM by Hibernate Tools 5.1.10.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ChitietxuatId generated by hbm2java
 */
@Embeddable
public class ChiTietXuatId implements java.io.Serializable {

	private int idPhieuXuat;
	private int idHangHoa;

	public ChiTietXuatId() {
	}

	public ChiTietXuatId(int idPhieuXuat, int idHangHoa) {
		this.idPhieuXuat = idPhieuXuat;
		this.idHangHoa = idHangHoa;
	}

	@Column(name = "ID_Phieu_Xuat", nullable = false)
	public int getIdPhieuXuat() {
		return this.idPhieuXuat;
	}

	public void setIdPhieuXuat(int idPhieuXuat) {
		this.idPhieuXuat = idPhieuXuat;
	}

	@Column(name = "ID_Hang_Hoa", nullable = false)
	public int getIdHangHoa() {
		return this.idHangHoa;
	}

	public void setIdHangHoa(int idHangHoa) {
		this.idHangHoa = idHangHoa;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ChiTietXuatId))
			return false;
		ChiTietXuatId castOther = (ChiTietXuatId) other;

		return (this.getIdPhieuXuat() == castOther.getIdPhieuXuat())
				&& (this.getIdHangHoa() == castOther.getIdHangHoa());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdPhieuXuat();
		result = 37 * result + this.getIdHangHoa();
		return result;
	}

}
