package doan.entity;
// Generated Jun 2, 2019 10:14:31 PM by Hibernate Tools 5.1.10.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ChitietnhapId generated by hbm2java
 */
@Embeddable
public class ChiTietNhapId implements java.io.Serializable {

	private int idPhieuNhap;
	private int idHangHoa;

	public ChiTietNhapId() {
	}

	public ChiTietNhapId(int idPhieuNhap, int idHangHoa) {
		this.idPhieuNhap = idPhieuNhap;
		this.idHangHoa = idHangHoa;
	}

	@Column(name = "ID_Phieu_Nhap", nullable = false)
	public int getIdPhieuNhap() {
		return this.idPhieuNhap;
	}

	public void setIdPhieuNhap(int idPhieuNhap) {
		this.idPhieuNhap = idPhieuNhap;
	}

	@Column(name = "ID_Hang_Hoa", nullable = false)
	public int getIdHangHoa() {
		return this.idHangHoa;
	}

	public void setIdHangHoa(int idHangHoa) {
		this.idHangHoa = idHangHoa;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ChiTietNhapId))
			return false;
		ChiTietNhapId castOther = (ChiTietNhapId) other;

		return (this.getIdPhieuNhap() == castOther.getIdPhieuNhap())
				&& (this.getIdHangHoa() == castOther.getIdHangHoa());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdPhieuNhap();
		result = 37 * result + this.getIdHangHoa();
		return result;
	}

}
