package doan.entity;
// Generated Jun 2, 2019 10:14:31 PM by Hibernate Tools 5.1.10.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ChitietdonhangId generated by hbm2java
 */
@Embeddable
public class ChiTietDonHangId implements java.io.Serializable {

	private int maHang;
	private int maDonHang;

	public ChiTietDonHangId() {
	}

	public ChiTietDonHangId(int maHang, int maDonHang) {
		this.maHang = maHang;
		this.maDonHang = maDonHang;
	}

	@Column(name = "MaHang", nullable = false)
	public int getMaHang() {
		return this.maHang;
	}

	public void setMaHang(int maHang) {
		this.maHang = maHang;
	}

	@Column(name = "MaDonHang", nullable = false)
	public int getMaDonHang() {
		return this.maDonHang;
	}

	public void setMaDonHang(int maDonHang) {
		this.maDonHang = maDonHang;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ChiTietDonHangId))
			return false;
		ChiTietDonHangId castOther = (ChiTietDonHangId) other;

		return (this.getMaHang() == castOther.getMaHang()) && (this.getMaDonHang() == castOther.getMaDonHang());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getMaHang();
		result = 37 * result + this.getMaDonHang();
		return result;
	}

}
