package doan.entity;
// Generated Jun 2, 2019 10:14:31 PM by Hibernate Tools 5.1.10.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Chitietxuat generated by hbm2java
 */
@Entity
@Table(name = "chitietxuat", catalog = "doan1")
public class ChiTietXuat implements java.io.Serializable {

	private ChiTietXuatId id;
	private Integer soLuong;
	private Integer donGia;

	public ChiTietXuat() {
	}

	public ChiTietXuat(ChiTietXuatId id) {
		this.id = id;
	}

	public ChiTietXuat(ChiTietXuatId id, Integer soLuong, Integer donGia) {
		this.id = id;
		this.soLuong = soLuong;
		this.donGia = donGia;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idPhieuXuat", column = @Column(name = "ID_Phieu_Xuat", nullable = false)),
			@AttributeOverride(name = "idHangHoa", column = @Column(name = "ID_Hang_Hoa", nullable = false)) })
	public ChiTietXuatId getId() {
		return this.id;
	}

	public void setId(ChiTietXuatId id) {
		this.id = id;
	}

	@Column(name = "So_Luong")
	public Integer getSoLuong() {
		return this.soLuong;
	}

	public void setSoLuong(Integer soLuong) {
		this.soLuong = soLuong;
	}

	@Column(name = "Don_Gia")
	public Integer getDonGia() {
		return this.donGia;
	}

	public void setDonGia(Integer donGia) {
		this.donGia = donGia;
	}

}
