package doan.entity;
// Generated Jun 2, 2019 10:14:31 PM by Hibernate Tools 5.1.10.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.format.annotation.DateTimeFormat;
import org.springframework.format.annotation.DateTimeFormat.ISO;

/**
 * Donhang generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "donhang", catalog = "doan1")
public class DonHang implements java.io.Serializable {

	private Integer maDonHang;
	private int maKhachHang;
	@DateTimeFormat(iso=ISO.DATE)
	private Date ngayDatHang;
	@DateTimeFormat(iso=ISO.DATE)
	private Date ngayGiaoHang;
	private String diaChi;
	private Float vat;
	private int tongThanhTien;
	private int maNhanVien;
	private String trangThai;

	public DonHang() {
	}

	public DonHang(int maKhachHang, Date ngayDatHang, Date ngayGiaoHang, String diaChi, int tongThanhTien,
			int maNhanVien) {
		this.maKhachHang = maKhachHang;
		this.ngayDatHang = ngayDatHang;
		this.ngayGiaoHang = ngayGiaoHang;
		this.diaChi = diaChi;
		this.tongThanhTien = tongThanhTien;
		this.maNhanVien = maNhanVien;
	}

	public DonHang(int maKhachHang, Date ngayDatHang, Date ngayGiaoHang, String diaChi, Float vat, int tongThanhTien,
			int maNhanVien, String trangThai) {
		this.maKhachHang = maKhachHang;
		this.ngayDatHang = ngayDatHang;
		this.ngayGiaoHang = ngayGiaoHang;
		this.diaChi = diaChi;
		this.vat = vat;
		this.tongThanhTien = tongThanhTien;
		this.maNhanVien = maNhanVien;
		this.trangThai = trangThai;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "MaDonHang", unique = true, nullable = false)
	public Integer getMaDonHang() {
		return this.maDonHang;
	}

	public void setMaDonHang(Integer maDonHang) {
		this.maDonHang = maDonHang;
	}

	@Column(name = "MaKhachHang", nullable = false)
	public int getMaKhachHang() {
		return this.maKhachHang;
	}

	public void setMaKhachHang(int maKhachHang) {
		this.maKhachHang = maKhachHang;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "NgayDatHang", nullable = false, length = 10)
	public Date getNgayDatHang() {
		return this.ngayDatHang;
	}

	public void setNgayDatHang(Date ngayDatHang) {
		this.ngayDatHang = ngayDatHang;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "NgayGiaoHang", nullable = false, length = 10)
	public Date getNgayGiaoHang() {
		return this.ngayGiaoHang;
	}

	public void setNgayGiaoHang(Date ngayGiaoHang) {
		this.ngayGiaoHang = ngayGiaoHang;
	}

	@Column(name = "DiaChi", nullable = false, length = 100)
	public String getDiaChi() {
		return this.diaChi;
	}

	public void setDiaChi(String diaChi) {
		this.diaChi = diaChi;
	}

	@Column(name = "VAT", precision = 12, scale = 0)
	public Float getVat() {
		return this.vat;
	}

	public void setVat(Float vat) {
		this.vat = vat;
	}

	@Column(name = "TongThanhTien", nullable = false)
	public int getTongThanhTien() {
		return this.tongThanhTien;
	}

	public void setTongThanhTien(int tongThanhTien) {
		this.tongThanhTien = tongThanhTien;
	}

	@Column(name = "MaNhanVien", nullable = false)
	public int getMaNhanVien() {
		return this.maNhanVien;
	}

	public void setMaNhanVien(int maNhanVien) {
		this.maNhanVien = maNhanVien;
	}

	@Column(name = "TrangThai", length = 20)
	public String getTrangThai() {
		return this.trangThai;
	}

	public void setTrangThai(String trangThai) {
		this.trangThai = trangThai;
	}

}
