package doan.entity;
// Generated Jun 2, 2019 10:14:31 PM by Hibernate Tools 5.1.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Hanghoa generated by hbm2java
 */
@Entity
@Table(name = "hanghoa", catalog = "doan1")
public class HangHoa implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer maHang;
	private String tenHang;
	private Integer nhomHang;
	private int donGia;
	private String donViTinh;
	private int soLuong;
	private String thongTin;
	private String nguonGoc;
	private String file;

	public HangHoa() {
	}

	public HangHoa(String tenHang, int donGia, String donViTinh, int soLuong) {
		this.tenHang = tenHang;
		this.donGia = donGia;
		this.donViTinh = donViTinh;
		this.soLuong = soLuong;
	}

	public HangHoa(String tenHang, Integer nhomHang, int donGia, String donViTinh, int soLuong, String thongTin,
			String nguonGoc, String file) {
		this.tenHang = tenHang;
		this.nhomHang = nhomHang;
		this.donGia = donGia;
		this.donViTinh = donViTinh;
		this.soLuong = soLuong;
		this.thongTin = thongTin;
		this.nguonGoc = nguonGoc;
		this.file = file;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "MaHang", unique = true, nullable = false)
	public Integer getMaHang() {
		return this.maHang;
	}

	public void setMaHang(Integer maHang) {
		this.maHang = maHang;
	}

	@Column(name = "TenHang", nullable = false, length = 100)
	public String getTenHang() {
		return this.tenHang;
	}

	public void setTenHang(String tenHang) {
		this.tenHang = tenHang;
	}

	@Column(name = "NhomHang")
	public Integer getNhomHang() {
		return this.nhomHang;
	}

	public void setNhomHang(Integer nhomHang) {
		this.nhomHang = nhomHang;
	}

	@Column(name = "DonGia", nullable = false)
	public int getDonGia() {
		return this.donGia;
	}

	public void setDonGia(int donGia) {
		this.donGia = donGia;
	}

	@Column(name = "DonViTinh", nullable = false, length = 10)
	public String getDonViTinh() {
		return this.donViTinh;
	}

	public void setDonViTinh(String donViTinh) {
		this.donViTinh = donViTinh;
	}

	@Column(name = "SoLuong", nullable = false)
	public int getSoLuong() {
		return this.soLuong;
	}

	public void setSoLuong(int soLuong) {
		this.soLuong = soLuong;
	}

	@Column(name = "ThongTin", length = 65535)
	public String getThongTin() {
		return this.thongTin;
	}

	public void setThongTin(String thongTin) {
		this.thongTin = thongTin;
	}

	@Column(name = "NguonGoc", length = 65535)
	public String getNguonGoc() {
		return this.nguonGoc;
	}

	public void setNguonGoc(String nguonGoc) {
		this.nguonGoc = nguonGoc;
	}

	@Column(name = "File", length = 255)
	public String getFile() {
		return this.file;
	}

	public void setFile(String file) {
		this.file = file;
	}

}
