package doan.entity;
// Generated Jun 10, 2019 4:54:32 AM by Hibernate Tools 5.1.10.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Khachhang generated by hbm2java
 */
@Entity
@Table(name = "khachhang", catalog = "doan1", uniqueConstraints = @UniqueConstraint(columnNames = "Users"))
public class KhachHang implements java.io.Serializable {

	private Integer maKhachHang;
	private String tenKhachHang;
	private String email;
	private String soDienThoai;
	private String users;
	private String matKhau;
	private String gioiTinh;
	private Date ngaySinh;
	private String diaChi;
	private Integer point;

	public KhachHang() {
	}

	public KhachHang(String tenKhachHang, String email, String users, String matKhau) {
		this.tenKhachHang = tenKhachHang;
		this.email = email;
		this.users = users;
		this.matKhau = matKhau;
	}

	public KhachHang(String tenKhachHang, String email, String soDienThoai, String users, String matKhau,
			String gioiTinh, Date ngaySinh, String diaChi, Integer point) {
		this.tenKhachHang = tenKhachHang;
		this.email = email;
		this.soDienThoai = soDienThoai;
		this.users = users;
		this.matKhau = matKhau;
		this.gioiTinh = gioiTinh;
		this.ngaySinh = ngaySinh;
		this.diaChi = diaChi;
		this.point = point;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "MaKhachHang", unique = true, nullable = false)
	public Integer getMaKhachHang() {
		return this.maKhachHang;
	}

	public void setMaKhachHang(Integer maKhachHang) {
		this.maKhachHang = maKhachHang;
	}

	@Column(name = "TenKhachHang", nullable = false, length = 100)
	public String getTenKhachHang() {
		return this.tenKhachHang;
	}

	public void setTenKhachHang(String tenKhachHang) {
		this.tenKhachHang = tenKhachHang;
	}

	@Column(name = "Email", nullable = false, length = 50)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "SoDienThoai", length = 10)
	public String getSoDienThoai() {
		return this.soDienThoai;
	}

	public void setSoDienThoai(String soDienThoai) {
		this.soDienThoai = soDienThoai;
	}

	@Column(name = "Users", unique = true, nullable = false, length = 30)
	public String getUsers() {
		return this.users;
	}

	public void setUsers(String users) {
		this.users = users;
	}

	@Column(name = "MatKhau", nullable = false, length = 20)
	public String getMatKhau() {
		return this.matKhau;
	}

	public void setMatKhau(String matKhau) {
		this.matKhau = matKhau;
	}

	@Column(name = "GioiTinh", length = 20)
	public String getGioiTinh() {
		return this.gioiTinh;
	}

	public void setGioiTinh(String gioiTinh) {
		this.gioiTinh = gioiTinh;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "NgaySinh", length = 10)
	public Date getNgaySinh() {
		return this.ngaySinh;
	}

	public void setNgaySinh(Date ngaySinh) {
		this.ngaySinh = ngaySinh;
	}

	@Column(name = "DiaChi", length = 100)
	public String getDiaChi() {
		return this.diaChi;
	}

	public void setDiaChi(String diaChi) {
		this.diaChi = diaChi;
	}

	@Column(name = "Point")
	public Integer getPoint() {
		return this.point;
	}

	public void setPoint(Integer point) {
		this.point = point;
	}

}
