package doan.entity;
// Generated Jun 2, 2019 10:14:31 PM by Hibernate Tools 5.1.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Nhacungcap generated by hbm2java
 */
@Entity
@Table(name = "nhacungcap", catalog = "doan1")
public class NhaCungCap implements java.io.Serializable {

	private Integer idNhaCungCap;
	private String tenNhaCungCap;
	private String diaChi;
	private String loaiMatHang;

	public NhaCungCap() {
	}

	public NhaCungCap(String tenNhaCungCap, String diaChi, String loaiMatHang) {
		this.tenNhaCungCap = tenNhaCungCap;
		this.diaChi = diaChi;
		this.loaiMatHang = loaiMatHang;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID_Nha_Cung_Cap", unique = true, nullable = false)
	public Integer getIdNhaCungCap() {
		return this.idNhaCungCap;
	}

	public void setIdNhaCungCap(Integer idNhaCungCap) {
		this.idNhaCungCap = idNhaCungCap;
	}

	@Column(name = "Ten_Nha_Cung_Cap", length = 45)
	public String getTenNhaCungCap() {
		return this.tenNhaCungCap;
	}

	public void setTenNhaCungCap(String tenNhaCungCap) {
		this.tenNhaCungCap = tenNhaCungCap;
	}

	@Column(name = "Dia_Chi", length = 45)
	public String getDiaChi() {
		return this.diaChi;
	}

	public void setDiaChi(String diaChi) {
		this.diaChi = diaChi;
	}

	@Column(name = "Loai_Mat_Hang", length = 45)
	public String getLoaiMatHang() {
		return this.loaiMatHang;
	}

	public void setLoaiMatHang(String loaiMatHang) {
		this.loaiMatHang = loaiMatHang;
	}

}
