package doan.entity;
// Generated Jun 2, 2019 10:14:31 PM by Hibernate Tools 5.1.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Nhomhang generated by hbm2java
 */
@Entity
@Table(name = "nhomhang", catalog = "doan1")
public class NhomHang implements java.io.Serializable {

	private Integer maNhom;
	private String tenNhom;
	private String ghiChu;

	public NhomHang() {
	}

	public NhomHang(String tenNhom, String ghiChu) {
		this.tenNhom = tenNhom;
		this.ghiChu = ghiChu;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "MaNhom", unique = true, nullable = false)
	public Integer getMaNhom() {
		return this.maNhom;
	}

	public void setMaNhom(Integer maNhom) {
		this.maNhom = maNhom;
	}

	@Column(name = "TenNhom", length = 45)
	public String getTenNhom() {
		return this.tenNhom;
	}

	public void setTenNhom(String tenNhom) {
		this.tenNhom = tenNhom;
	}

	@Column(name = "GhiChu", length = 65535)
	public String getGhiChu() {
		return this.ghiChu;
	}

	public void setGhiChu(String ghiChu) {
		this.ghiChu = ghiChu;
	}

}
